src/main/java/seoultech/capstone/menjil/Hello.java
src/main/java/seoultech/capstone/menjil/HelloController.java
src/main/java/seoultech/capstone/menjil/global/config/SecurityConfig.java
src/main/java/seoultech/capstone/menjil/global/config/WebConfig.java

- nextjs 프록시 설정 없이 서버에서 해결하는 방식으로
- Hello, HelloController는 GET, POST 요청 테스트를 위해 남겨놓음

feat: Solve CORS issues

---

src/main/java/seoultech/capstone/menjil/domain/auth/api/OAuthController.java
src/main/java/seoultech/capstone/menjil/domain/auth/application/OAuthService.java
src/main/java/seoultech/capstone/menjil/domain/user/application/UserService.java
src/main/java/seoultech/capstone/menjil/global/common/JwtUtils.java
src/main/java/seoultech/capstone/menjil/global/config/SecurityConfig.java
src/main/java/seoultech/capstone/menjil/global/filter/CustomCorsFilter.java
src/test/java/seoultech/capstone/menjil/domain/user/api/UserControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/user/application/UserServiceTest.java

login 로직은 구현하지 않았지만, 그 외 기타 코드 부분 수정본 merge

---

src/main/java/seoultech/capstone/menjil/domain/user/domain/User.java
src/main/java/seoultech/capstone/menjil/domain/user/dto/UserDto.java
src/main/java/seoultech/capstone/menjil/domain/user/dto/request/UserRequestDto.java

feat: birthDate column을 birthYear, birthMonth로 분리

---

.github/workflows/develop.yml
.gitignore
src/main/java/seoultech/capstone/menjil/domain/auth/application/OAuthService.java
src/main/java/seoultech/capstone/menjil/domain/user/application/UserService.java
src/main/java/seoultech/capstone/menjil/domain/user/dao/UserRepository.java
src/main/java/seoultech/capstone/menjil/domain/user/domain/User.java
src/main/java/seoultech/capstone/menjil/global/common/JwtUtils.java
src/main/resources/application.yml
src/test/java/seoultech/capstone/menjil/domain/user/api/UserControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/user/application/UserServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/user/dao/UserRepositoryTest.java

- UserController
- UserRepository
- UserService
- Dev Server Port number change

현재까지 진행 내용 Merge

---

src/main/java/seoultech/capstone/menjil/domain/user/domain/User.java
src/main/java/seoultech/capstone/menjil/domain/user/dto/UserDto.java
src/main/java/seoultech/capstone/menjil/domain/user/dto/request/UserRequestDto.java
src/test/java/seoultech/capstone/menjil/domain/user/api/UserControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/user/application/UserServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/user/dao/UserRepositoryTest.java

#18 - feat: Add graduateMonth in user data

---

build.gradle
src/main/java/seoultech/capstone/menjil/domain/auth/api/AuthController.java
src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dao/UserRepository.java
src/main/java/seoultech/capstone/menjil/domain/auth/domain/User.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/request/SignInRequestDto.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/request/SignUpRequestDto.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/response/SignInResponseDto.java
src/main/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProvider.java
src/main/java/seoultech/capstone/menjil/global/config/WebConfig.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/filter/CustomCorsFilter.java
src/main/java/seoultech/capstone/menjil/global/filter/JwtAuthenticationFilter.java
src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProviderTest.java

- #24 에서 Redis 연동 빼고 구현 완료
- Redis 연동 후 한 번에 merge 하려고 하였으나, 중간에 다른 기능을 변경해야 해서 merge

24 feat login and authentication-1차

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dao/TokenRepository.java
src/main/java/seoultech/capstone/menjil/domain/auth/domain/RefreshToken.java
src/main/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProvider.java
src/main/java/seoultech/capstone/menjil/global/config/WebConfig.java
src/main/java/seoultech/capstone/menjil/global/filter/CustomCorsFilter.java
src/main/java/seoultech/capstone/menjil/global/filter/JwtAuthenticationFilter.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/dao/TokenRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/dao/UserRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProviderTest.java

- 서버에서 Access, Refresh Token 을 클라이언트로부터 받아서 처리하는 로직 모두 구현
- Test Code 작성
- Access Token의 경우 클라이언트에서 만료 여부를 검증하도록 코드가 수정되야할 가능성이 존재함.

24 feat login and authentication-2차

---

.github/workflows/develop.yml

develop branch 추가 및 main.yml 파일 수정

cicd: add github action in develop branch and fix main.yml

---

src/main/java/seoultech/capstone/menjil/domain/auth/TokenTestController.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/request/SignUpRequestDto.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/response/SignInResponseDto.java
src/main/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProvider.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/main/java/seoultech/capstone/menjil/global/filter/JwtAuthenticationFilter.java
src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/global/filter/JwtAuthenticationFilterTest.java

- #30 에서, [https://inpa.tistory.com/entry/WEB-📚-Access-Token-Refresh-Token-원리-feat-JWT](https://inpa.tistory.com/entry/WEB-%F0%9F%93%9A-Access-Token-Refresh-Token-%EC%9B%90%EB%A6%AC-feat-JWT) 링크를 참고해서 해당 절차로 인증 절차 변경
- 그림 참고

24 feat login and authentication-final-v2

---

.github/workflows/code-coverage.yml

fix: codecov configure

---

.github/workflows/code-coverage.yml

fix codecov configure test

---

build.gradle
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/ChatGptService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/config/MongoConfig.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/ChatMessage.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/Room.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/SenderType.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/MessageDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/RoomDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessagesResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/MenjilApplicationTests.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepositoryTest.java

- #29 에 이어서, Flask 서버로 보내기 이전까지는 기능 구현
- 채팅 플로우가 나오면, 해당 플로우에 맞춰서 개발
- Flask 서버 로직 개발

chatbot : 2차 구현

---

build.gradle
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/ChatGptService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/RoomDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/FlaskRequestDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/ChatGptResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/RoomListResponse.java
src/main/java/seoultech/capstone/menjil/global/config/WebClientConfig.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/ChatGptServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java

21 feat chatbot-1차 구현 마무리

---

build.gradle
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/ChatGptService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/config/MongoConfig.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/ChatMessage.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/Room.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/SenderType.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/MessageDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/RoomDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/FlaskRequestDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/ChatGptResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessagesResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/RoomListResponse.java
src/main/java/seoultech/capstone/menjil/global/config/WebClientConfig.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/MenjilApplicationTests.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/ChatGptServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepositoryTest.java

chatbot 1차 구현 마무리-QUESTION 전까지

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java

45 bug response code error in roomcontroller

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceExceptionTest.java

- related to save() method in JPA
- #47

#47 - test: Create check CustomExceptionTest

---

src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/dao/TokenRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProviderTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/ChatGptServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/global/filter/JwtAuthenticationFilterTest.java

#50 - refactor: Rename of test function

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/RoomDto.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java

#53 - fix: roomId를 클라이언트로부터 받도록 수정

---

src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java

- #53 수정 이후, 불필요한(UUID 생성과 관련된) 코드 제거

#53 - chore: 사용하지 않는 코드 제거

---

codecov.yml

- #56  : codecov.yml file Update

#56 - feat: Update codecov.yml

---

.github/workflows/code-coverage.yml
.github/workflows/develop.yml
.github/workflows/main.yml

59 feat migrate test database from aws to local

---

.github/workflows/code-coverage.yml
.github/workflows/develop.yml
.github/workflows/main.yml

- #64 
- #62 PR 문제 해결 되었으리라 생각

#64 - fix: Add MySQL connection verify code

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/response/SignInResponseDto.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java

#63 - feat: 로그인시 정보를 추가로 보내도록 수정

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dao/UserRepository.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/response/SignInResponseDto.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/RoomInfoDto.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/api/dto/UserInfoResponseDto.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/MentorInfoDto.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/UserInfoDto.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/main/api/MainPageControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

#58 Complete

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageListResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java

73 feat 멘티에게 질문을 받아서 처리하는 로직(Test code 미완성)

---

src/main/java/seoultech/capstone/menjil/domain/auth/api/AuthController.java
src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/request/SignInRequest.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/request/SignUpRequest.java
src/main/java/seoultech/capstone/menjil/domain/auth/dto/response/SignInResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/AwsLambdaRequest.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/MessageRequest.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/AwsLambdaResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageListResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/RoomInfoResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/MentorInfoResponse.java
src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/main/api/MainPageControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

#78 - refactor: Rename dto class and methods

---

src/main/java/seoultech/capstone/menjil/domain/auth/api/AuthController.java
src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/MessageType.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/AwsLambdaResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/main/api/MainPageControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

#73 
* AWS Lambda로부터, similarity_percent 받아서 처리하는 부분 수정
* 그 외 잡다한 내용 수정(자세한 사항은 커밋 참고)

73 feat question logic(세부사항 추가, 테스트 코드 미작성)

---

src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/MessageRequest.java

#82 - fix: Fix Validation @NotBlank error in enum type

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/RoomInfoResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/main/api/MainPageControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

* And order by lastMessageTime DESC
- #84

#84 - feat: Replace lastMessagedTimeOfHour to lastMessageTime

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java

fix: send stomp message: /queue -> /pub

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java

* feat: 클라이언트가 입력한 메시지도 다시 클라이언트로 저장하도록 로직 수정

#89 - feat: 클라이언트가 입력한 메시지도 다시 클라이언트로 저장하도록 로직 수정

---

src/main/java/seoultech/capstone/menjil/domain/follow/api/FollowController.java
src/main/java/seoultech/capstone/menjil/domain/follow/application/FollowService.java
src/main/java/seoultech/capstone/menjil/domain/follow/dao/Follow.java
src/main/java/seoultech/capstone/menjil/domain/follow/domain/FollowRepository.java
src/main/java/seoultech/capstone/menjil/domain/follow/dto/request/FollowRequest.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/FollowListResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/MentorInfoResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java

81 feat interest mentors(기능 구현)

---

src/main/java/seoultech/capstone/menjil/domain/follow/api/FollowController.java
src/main/java/seoultech/capstone/menjil/domain/follow/application/FollowService.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/follow/api/FollowControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/follow/application/FollowServiceTest.java

95 revise follow

---

src/main/java/seoultech/capstone/menjil/domain/chat/dao/QaListRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/QaList.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/MentorInfoResponse.java

#97 - feat: 메인 페이지] 멘토의 최근 답변한 질문 리스트

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/global/common/dto/ApiResponse.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/MessageControllerSpringBootTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerSpringBootTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java

99 refactor domain of chat abstraction level

---

src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/AwsLambdaRequest.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/AwsLambdaResponse.java

- #101 에서,
-  4번 '멘토에게 질문하기' 항목 추가
- 변수명 수정: threeLineSummaryMessage -> question_summary

#101 - feat:  4번 '멘토에게 질문하기' 항목 추가

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/ChatMessage.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/MessageType.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/AwsLambdaRequest.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/AwsLambdaResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageListResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerSpringBootTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/dao/RoomRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/follow/application/FollowServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

101 feat chatting logic

---

src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/AwsLambdaResponse.java

#106 - fix: type mistmatch

---

src/main/java/seoultech/capstone/menjil/domain/chat/dao/QaListRepository.java
src/main/java/seoultech/capstone/menjil/domain/follow/dao/FollowRepository.java
src/main/java/seoultech/capstone/menjil/domain/following/api/FollowingController.java
src/main/java/seoultech/capstone/menjil/domain/following/application/FollowingService.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/FollowingUserInfo.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/response/FollowingMentorResponse.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java

#105 - feat: GET my following mentor list(not test code)

---

src/main/java/seoultech/capstone/menjil/domain/chat/domain/QaList.java
src/main/java/seoultech/capstone/menjil/domain/follow/dao/FollowRepository.java
src/main/java/seoultech/capstone/menjil/domain/main/api/MainPageController.java
src/main/java/seoultech/capstone/menjil/domain/main/application/MainPageService.java
src/main/java/seoultech/capstone/menjil/domain/main/dto/response/FollowUserResponse.java
src/test/java/seoultech/capstone/menjil/domain/main/api/MainPageControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/main/application/MainPageServiceTest.java

* MainPageControllerTest, MainPageServiceTest code coverage 100% complete
- #108

#108 - feat: 채팅방 전체 목록을 불러오는 API 추가 및 채팅 목록을 불러오는 API 제거

---

src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageListResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageResponse.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java

* DTO Response 객체에 roomId를 포함하도록 변경
* 피그마 양식에 맞추어서 AI_RESPONSE 메시지 수정
* 테스트 코드 일부 수정

#108 - feat: Response에 roomId 포함 및 그 외 수정

---

src/main/java/seoultech/capstone/menjil/domain/auth/api/AuthController.java
src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/dao/UserRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/follow/api/FollowController.java
src/main/java/seoultech/capstone/menjil/domain/follow/application/FollowService.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorIntValue.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessIntValue.java
src/test/java/seoultech/capstone/menjil/domain/auth/api/AuthControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/application/AuthServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/auth/dao/UserRepositoryTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/follow/api/FollowControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/follow/application/FollowServiceTest.java

#113 refactor int code를 global로 관리

---

src/main/java/seoultech/capstone/menjil/domain/chat/dao/QaListRepository.java
src/main/java/seoultech/capstone/menjil/domain/following/api/FollowingController.java
src/main/java/seoultech/capstone/menjil/domain/following/application/FollowingService.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/FollowingQaDto.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/FollowingUserDto.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/FollowingUserInfoDto.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/response/FollowingMentorInfoResponse.java
src/main/java/seoultech/capstone/menjil/domain/following/dto/response/FollowingMentorResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/following/application/FollowingServiceTest.java

- 팔로잉 페이지 입장 시, 나의 팔로잉 멘토 조회
- 팔로잉한 멘토의 상세 정보 조회
- 팔로잉한 멘토 상세 정보 조회 Test code 작성

105 feat following page - 기능 구현 완료, 테스트 코드 미완성

---

src/main/java/seoultech/capstone/menjil/domain/auth/application/AuthService.java
src/main/java/seoultech/capstone/menjil/domain/auth/jwt/JwtTokenProvider.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageController.java
src/main/java/seoultech/capstone/menjil/domain/chat/api/RoomController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/ChatGptService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/RoomService.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/MessageType.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageOrderResponse.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageResponse.java
src/main/java/seoultech/capstone/menjil/domain/follow/api/FollowController.java
src/main/java/seoultech/capstone/menjil/domain/following/application/FollowingService.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/MessageControllerSpringBootTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerSpringBootTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/api/RoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/RoomServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/follow/api/FollowControllerTest.java

116 feat chat logic 2: 일부 작업 완료

---

src/main/java/seoultech/capstone/menjil/domain/chat/api/MessageRatingController.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/AwsLambdaClient.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageRatingService.java
src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/QaListRepository.java
src/main/java/seoultech/capstone/menjil/domain/chat/domain/QaList.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/request/MessageClickIncViewsAndLikesRequest.java
src/main/java/seoultech/capstone/menjil/domain/chat/dto/response/MessageClickIncViewsAndLikesResponse.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/main/java/seoultech/capstone/menjil/global/exception/SuccessCode.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageRatingServiceTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceExceptionTest.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageServiceTest.java

116 feat chat logic 2(Complete)

---

src/main/java/seoultech/capstone/menjil/domain/chat/application/MessageRatingService.java
src/main/java/seoultech/capstone/menjil/domain/chat/dao/MessageRepository.java
src/main/java/seoultech/capstone/menjil/global/exception/ErrorCode.java
src/test/java/seoultech/capstone/menjil/domain/chat/application/MessageRatingServiceTest.java

- MessageRatingService 테스트 코드 수정

test: MessageRatingService 테스트 코드 수정

---

.github/workflows/ci-dev.yml

#133 - feat: write 권한 추가

---

.github/workflows/build-on-pr.yml
.github/workflows/cd-main.yml
.github/workflows/ci-develop.yml

1. cd-main.yml: main branch로 push될 때 CD 수행
2. ci-develop.yml: develop branch로 push될 때 CI 실행
3. build-on-pr.yml: pr시 test 결과에 대한 report 제공, codecov 실행
- #133

#133 - feat: CI/CD 수정

---

.github/workflows/build-on-pr.yml
.github/workflows/ci-develop.yml

[Workflow 에서 오류난 부분](https://github.com/Menjil-Menjil/Menjil-BE/actions/runs/7354379660)
오류 메시지
* every step must define a `uses` or `run` key

fix: GitHub Action CI 오류

---

src/docs/asciidoc/index.adoc
src/test/java/seoultech/capstone/menjil/docs/chatbot/ChatBotRoomControllerDocsTest.java
src/test/java/seoultech/capstone/menjil/domain/chatbot/api/ChatBotRoomControllerTest.java
src/test/java/seoultech/capstone/menjil/domain/chatbot/application/ChatBotRoomServiceTest.java

test: getAllChatBotRooms 메서드 테스트 코드를 추가로 작성한다(#143)
